### ISSUE TITLE
Please make it available also in the server side

### ISSUE THREAD

**Issue by ccfiel** [harrisonhunter/papa-parse-meteor#5]
I have notice in this line of code https://github.com/harrisonhunter/papa-parse-meteor/blob/master/package.js#L11 that the package is only available for client only. Can you please make it also available for the server.

**Comment by Nullpo** [comment]
+1

**Comment by kenken17** [comment]
+1

**Comment by rhyslbw** [comment]
+1

**Comment by harrisonhunter** [comment]
the original package is meant for in browser csv parsing and is packaged in jquery which is why I also put in the baby parse package (which is meant for running in node.js).

**Comment by harrisonhunter** [comment]
Resolved with version 1.1, let me know if you have any issues
