### ISSUE TITLE
ReferenceError: Package is not defined when `worker: true`

### ISSUE THREAD

**Issue by vladgolubev** [harrisonhunter/papa-parse-meteor#8]
Whenever I try to set `worker: true` property I get this error in console:
`Uncaught ReferenceError: Package is not defined`

![screenshot from 2015-12-30 17-26-02](https://cloud.githubusercontent.com/assets/3817380/12052720/6b723d34-af1a-11e5-9d53-3e91434b2d87.png)

**Comment by brundage** [comment]
+1 
v1.0.19

**Comment by mjwheatley** [comment]
+1
v1.1.1

**Comment by kartojal** [comment]
Same here!

**Comment by denodaeus** [comment]
+1

**Comment by ethesx** [comment]
Closed for what reason?  Fixed in new release?

**Comment by leosco** [comment]
I can confirm that this still _doesn't work_ in the latest release `4.1.2` that I just installed :(
However, as I'm using Meteor in most of my projects, this may be a problem/limitation with the `meteor-node-stubs` package, not papaparse itself.

**Comment by andreasteffanoni** [comment]
Same to me!

**Comment by ryanmtaylor** [comment]
I _think_ this is an issue for lower Meteor versions.  I'm running Meteor 1.3.2.4

**Comment by aTylerRice** [comment]
I'm getting this error on meteor version METEOR@1.4.2.3

**Comment by janjackson** [comment]
same here on Meteor 1.5.1

**Comment by leosco** [comment]
iirc neither this, nor the original Papaparse project is being maintained anymore, so it may be RIP unless someone can fork it and provide a solution.
